[project]
name = "beeper"
version = "1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydub~=0.25",
    "pyttsx3~=2.98",
    "pyaudio~=0.2",
]

[project.urls]
Homepage = "https://github.com/davidhyman/beep_test"
